name = "RNAstructure"
uuid = "daac0927-178b-45a3-8088-242e3d097d58"
authors = ["Marco Matthies <marco.matthies@gmail.com>"]
version = "0.3.6"

[deps]
RNAstructure_jll = "82b15e58-31a0-525e-9c90-1fc374f3aa86"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
RNAstructure_jll = "6.4.0"
Unitful = "1.12"
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
